export interface Customer {
            email :string,
            _website :string,
            _store :string,
            account_type  :string,
            created_at :string,
            accounttype:string,
            created_in :Date,
            dob	: Date,
            firstname :string	,
            gender :string	,
            lastname :string,
            middlename :string	,
            password :string,
            company :string,
            address :string ,
            city :string,
            state :string,
            fax :string,
            province :string,
            postcode :number,
            country  :string,
            telephone   :string,
}
