apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontend-sword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-sword
  template:
    metadata:
      labels:
        app: frontend-sword
    spec:
      containers:
      - image: gcr.io/fillcraft-swards/frontend_swards_img:latest
        imagePullPolicy: Always
        name: frontend-sword
        ports:
        - containerPort: 4200
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: frontend-sword
spec:
    type: LoadBalancer
    ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
    selector:
        app: frontend-sword
---